[feat] 쿠폰 관련 기본설정입니다.
mitoconcrete/waiting-catch-project pull request #112
Opened 2023-02-10 11:08 UTC by rianbowgift

빨리 확인해주세요

2023-02-10 11:49 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/entity/CouponCreator.java
> +    private CouponRoleEnum discount_type;
@rianbowgift calmelCase 로 변경해주세요

2023-02-10 11:49 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/enums/CouponRoleEnum.java
> +    PRICE(Authority.PRICE),
@rianbowgift 그냥 PRICE, PERCENT 만 남겨주세요

2023-02-10 11:49 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +public class CouponCreatorServiceImpl implements InternalCouponCreatorService, CouponCreatorService{
@rianbowgift 인터페이스 순서를 맞춰주시고, 포맷을 맞춰주세요!

2023-02-10 12:00 UTC, mitoconcrete requested changes

2023-02-10 12:00 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/InternalCouponCreatorServiceImpl.java
> +public class InternalCouponCreatorServiceImpl implements InternalCouponCreatorService, CouponCreatorService {
순서가 안바꼈어용

2023-02-10 12:00 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/InternalUserCouponServiceImpl.java
> +public class InternalUserCouponServiceImpl implements InternalUserCouponService, UserCouponService {
여기는 원래 순서가 맞았는데, 바꼈어요

2023-02-10 12:00 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/event/InternalEventServiceImpl.java
> +public class InternalEventServiceImpl implements InternalEventService, EventService {
순서변경해주세욥

2023-02-10 12:11 UTC, mitoconcrete requested changes

2023-02-10 12:16 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/EventServiceRepository.java
> +@Repository
@rianbowgift @Repository 어노테이션은 생략 가능합니다.

2023-02-10 12:16 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/UserCouponRepository.java
> +@Repository
@rianbowgift @Repository 어노테이션은 생략 가능합니다.

2023-02-11 04:11 UTC, developer-Park approved these changes

2023-02-11 04:23 UTC, mitoconcrete approved these changes

2023-02-11 07:31 UTC, s-jje approved these changes

2023-02-11 08:35 UTC, jk891113 approved these changes

2023-02-11 09:21 UTC, merged