Init/restaurant han
mitoconcrete/waiting-catch-project pull request #113
Opened 2023-02-10 11:39 UTC by jk891113

Restaurant 관련 엔티티 및 클래스 생성 완료 했습니다.

2023-02-10 11:54 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/RestaurantCategory.java
> +    @ManyToOne
@jk891113 fetch type을 lazy로 설정해 주세요.

2023-02-10 11:54 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/RestaurantCategory.java
> +    @ManyToOne
@jk891113  fetch type을 lazy로 설정해 주세요.

2023-02-10 11:54 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/menu/MenuServiceImpl.java
> +public class MenuServiceImpl implements MenuService, InternalMenuService{
@jk891113 코드 컨벤션을 지켜 주세요.

2023-02-10 11:54 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/restaurant/RestaurantServiceImpl.java
> +public class RestaurantServiceImpl implements RestaurantService, InternalRestaurantService{
@jk891113  코드 컨벤션을 지켜 주세요.

2023-02-10 12:02 UTC, mitoconcrete requested changes

2023-02-11 04:12 UTC, developer-Park approved these changes

2023-02-11 04:24 UTC, mitoconcrete approved these changes

2023-02-11 07:34 UTC, s-jje approved these changes

2023-02-12 12:12 UTC, mitoconcrete approved these changes

2023-02-13 00:06 UTC, rianbowgift reviewed
.

2023-02-13 00:06 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
> +import javax.persistence.*;
@rianbowgift 스코프 최소화 라는게 어떤 의미죠? 구체적으로 서술해주세요.
import team.waitingcatch.app.common.* 와 같이 표시하는 걸 말씀하시는 건가요?

2023-02-13 00:08 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
> +import javax.persistence.*;
네 맞습니다.
이부분은 jk891113님이 수정하셨다고 하네요

2023-02-13 00:11 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
> +import javax.persistence.*;
@rianbowgift 넵 사실 이부분은 가독의 문제라 나중에 수정해도 될 것 같습니다.
[이 글](https://stackoverflow.com/a/187467)에 따르면 퍼포먼스에 크게 차이는 없다고 합니다. 자바의 정석에서도 봤던 것 같아요.

2023-02-13 00:12 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
> +import javax.persistence.*;
일단 코드가 합쳐졌을때 문제를 일으킬만한 요소가 있는지 우선적으로 확인해주세요!

2023-02-13 00:49 UTC, mitoconcrete approved these changes

2023-02-13 01:01 UTC, rianbowgift approved these changes

2023-02-13 01:03 UTC, merged