Init/restaurant park
mitoconcrete/waiting-catch-project pull request #114
Opened 2023-02-10 11:44 UTC by developer-Park

2023-02-10 12:27 UTC, mitoconcrete requested changes

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/BlackList.java
> +	@JoinColumn(name = "restaurant_id",nullable = false)
Lazy 설정을 추가해주세요.

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/BlackList.java
> +	@JoinColumn(name = "user_id",nullable = false)
Lazy 설정을 추가해주세요.

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/BlackListRequest.java
> +	private Restaurant restaurant;
lazy 설정을 추가해주세요.

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/BlackListRequest.java
> +	private User user;
lazy 설정을 추가해주세요.

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRepository.java
> +@Repository
빼주세용

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +@Repository
빼주세요

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/impl/BlackListRequestServiceImpl.java
> +public class BlackListRequestServiceImpl implements BlackListRequestService, InnerBlackListRequestService {
Inner -> Internal 변경해주세요!

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/impl/BlackListServiceImpl.java
> +public class BlackListServiceImpl implements BlackListService, InnerBlackListService {
Inner -> Internal 변경해주세요!

2023-02-10 12:27 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/impl/SellerManagementServiceImpl.java
> +public class SellerManagementServiceImpl implements SellerManagementService, InnerSellerManagementService {
Inner -> Internal 변경해주세요!

2023-02-11 04:19 UTC, mitoconcrete approved these changes

2023-02-11 07:35 UTC, s-jje approved these changes

2023-02-11 08:35 UTC, jk891113 approved these changes

2023-02-13 00:07 UTC, rianbowgift reviewed
.

2023-02-13 00:55 UTC, mitoconcrete approved these changes

2023-02-13 01:06 UTC, rianbowgift approved these changes

2023-02-13 01:29 UTC, mitoconcrete approved these changes

2023-02-13 01:30 UTC, jk891113 approved these changes

2023-02-13 01:30 UTC, merged