ì[refactor] businessLicenseNo 위치 변경
mitoconcrete/waiting-catch-project pull request #119
Opened 2023-02-13 06:24 UTC by developer-Park

해당 변수 위치 변경

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +	public List<GetDemandSignUpSellerResponse> getDemandSignUpSellers() {
@developer-Park 페이징 처리 추가해 주세요.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		}
@developer-Park ifPresent()를 사용하면 가독성이 더 좋을 것 같습니다!

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/SellerManagement.java
> +
@developer-Park 빈 라인 제거해 주세요.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerManagementController.java
> +	@DeleteMapping(path = "/admin/seller-managements/{sellerManagementId}")
@developer-Park 판매자 요청 상태를 변경하는 api이므로 PostMapping 또는 PutMapping이 적절할 것 같습니다.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		sellerManagementRepository.save(sellerManagement);
@developer-Park update 시에는 아래와 같은 이유로 인해 dirty checking으로 변경되도록 두는 것이 좋을 것 같습니다.

1. JPA의 장점 중 하나가 java collection을 다루는 것처럼 사용할 수 있다는 것 (ex. list.set())
2. 불필요한 로직이 실행될 수 있다는 점 (em.merge())
3. update가 수행됨을 메소드 명에서 명시적으로 알 수 있다는 점

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		sellerManagementRepository.save(sellerManagement);
@developer-Park update 시에는 아래와 같은 이유로 인해 dirty checking으로 변경되도록 두는 것이 좋을 것 같습니다.

1. JPA의 장점 중 하나가 java collection을 다루는 것처럼 사용할 수 있다는 것 (ex. list.set())
2. 불필요한 로직이 실행될 수 있다는 점 (em.merge())
3. update가 수행됨을 메소드 명에서 명시적으로 알 수 있다는 점

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		if (sellerManagement.getStatus() == AcceptedStatusEnum.REJECTION) {
@developer-Park 이 로직은 entity에 위임하는 것이 좋아보입니다.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
> +	private Integer capacity;
@developer-Park primitive 타입을 사용해 주세요.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerManagementController.java
> +public class SellerManagementController {
@developer-Park request dto에 대한 validation을 추가해 주세요

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/ApproveSignUpSellerManagementEntityPassToRestaurantEntityRequest.java
> +public class ApproveSignUpSellerManagementEntityPassToRestaurantEntityRequest {
@developer-Park validation 추가해 주세요.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/DemandSignUpSellerControllerRequest.java
> +public class DemandSignUpSellerControllerRequest {
@developer-Park validation 추가해 주세요.

2023-02-13 23:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/DemandSignUpSellerServiceRequest.java
> +public class DemandSignUpSellerServiceRequest {
@developer-Park validation 추가해 주세요.

2023-02-14 02:10 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		User seller = userService.createSeller(userCreateServiceRequest);
@developer-Park 이건 createUser을 사용해주시고, dto에 role에 seller를 추가하는 형태로 바꿔주시면 될것같아요!

2023-02-14 02:20 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/RejectSignUpSellerServiceRequest.java
> +@NoArgsConstructor
@developer-Park 기본생성자는 없어도 될것같아요.
service dto의 값은 변경될 일이 없기때문에,  멤버변수의 타입은 final로 두시고 @RequiredArgsConstructor을 사용하심으로서 가독성을 올릴수있을것같습니다.

2023-02-14 02:39 UTC, mitoconcrete requested changes

2023-02-14 02:39 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/DemandSignUpSellerServiceRequest.java
> +public class DemandSignUpSellerServiceRequest {
@developer-Park 기본생성자는 없어도 될것같아요.
service dto의 값은 변경될 일이 없기때문에, 멤버변수의 타입은 final로 두시고 @requiredargsconstructor을 사용하심으로서 가독성을 올리고 오사용을 막을 수 있을 것 같습니다.

2023-02-14 02:39 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/ApproveSignUpSellerServiceRequest.java
> +@NoArgsConstructor
Pending
@developer-Park 기본생성자는 없어도 될것같아요.
service dto의 값은 변경될 일이 없기때문에, 멤버변수의 타입은 final로 두시고 @requiredargsconstructor을 사용하심으로서 가독성을 올리고 오사용을 막을 수 있을 것 같습니다.

2023-02-14 02:39 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/ApproveSignUpSellerResponse.java
> +public class ApproveSignUpSellerResponse {
Pending
@developer-Park 기본생성자는 없어도 될것같아요.
service dto의 값은 변경될 일이 없기때문에, 멤버변수의 타입은 final로 두시고 @requiredargsconstructor을 사용하심으로서 가독성을 올리고 오사용을 막을 수 있을 것 같습니다.

2023-02-14 02:39 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/GetDemandSignUpSellerResponse.java
> +@NoArgsConstructor
Pending
@developer-Park 기본생성자는 없어도 될것같아요.
service dto의 값은 변경될 일이 없기때문에, 멤버변수의 타입은 final로 두시고 @requiredargsconstructor을 사용하심으로서 가독성을 올리고 오사용을 막을 수 있을 것 같습니다.

2023-02-14 02:39 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/ApproveSignUpSellerManagementEntityPassToRestaurantEntityRequest.java
> +public class ApproveSignUpSellerManagementEntityPassToRestaurantEntityRequest {
@developer-Park 해당 dto는 엔티티로 값을 전달하기 위한 dto로 파악했어요.
저는 타레이어는 상관없지만 개인적으로 업데이트 에 대한건 엔티티의 멤버변수에 의존되어야한다고 생각해서, 서비스레이어에서 데이터를 일일히 넣어주는 편이긴 하거든요. dto를 만들게되면 dto안의 매개변수에 의존하게 되어서 nullable한 값이 들어가거나, 사용하지 않은 필드가 남아있는등의 이슈가 있다고 생긱합니다
제 설명이 납득되시면 적용해주시고, 그렇지 않다면 당장 기능상에는 이슈가 없어서 두셔도 좋을것같습니다

2023-02-14 02:50 UTC, developer-Park commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +	public List<GetDemandSignUpSellerResponse> getDemandSignUpSellers() {
페이징은 추후 개발 예정

2023-02-14 02:55 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerManagementController.java
> +	@GetMapping(path = "/admin/seller-managements")
"path="는 생략해도 될것같네요

2023-02-14 02:55 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		sellerManagementRepository.save(sellerManagement);
협업과정에서 save등이 명시되어있지않을시 혼동될수 있기때문에 쓰는것도 괜찮다고 들었습니다.(승민튜터님은 명시적으로 항상 적는다고 하시네요)

2023-02-14 02:55 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/user/service/InternalUserService.java
> +	User _findByUsername(String username);
어떤것을 불러오는지 이름에 명시적으로 추가하는것이 좋을듯합니다. 예를들어 유저이름으로 레스토랑을찾는다면 _getRestaurantByUsername 정도로 하는게 좋을듯하네요

2023-02-14 05:17 UTC, mitoconcrete requested changes

2023-02-14 05:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		Optional<User> user = internalUserService._findByUsername(demandSignupSellerServiceRequest.getUsername());
@developer-Park _getUserByUsername 을 사용해주시면 되고, 제가 service에서 Duplicate 핸들링을 하고 있으니, 그냥 User만 꺼내서 쓰시면 됩니다.

2023-02-14 05:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
> +		Optional<User> userEmail = internalUserService._findByEmail(demandSignupSellerServiceRequest.getEmail());
@developer-Park _getUserByEmail 을 사용해주시면 되고, 제가 service에서 Duplicate 핸들링을 하고 있으니, 그냥 User만 꺼내서 쓰시면 됩니다.

2023-02-14 08:08 UTC, jk891113 approved these changes

2023-02-14 08:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestseller/SellerManagementServiceImpl.java
>  			= new UserCreateServiceRequest(sellerManagement, uuidPassword);
@developer-Park 셀러 도메인에서 Dto네이밍을 아래와 같이 변경해주세요!
CreateUserServiceRequest -> UserCreateServiceRequest
UserRoleEnum role
String name
String email
String username
String password,
String nickname,
String phoneNumber

2023-02-14 09:22 UTC, mitoconcrete approved these changes

2023-02-14 09:22 UTC, s-jje approved these changes

2023-02-14 14:30 UTC, rianbowgift approved these changes

2023-02-15 00:26 UTC, merged