[feat] Category 도메인
mitoconcrete/waiting-catch-project pull request #121
Opened 2023-02-13 14:39 UTC by jk891113

Category 도메인 기능 구현 완료 했습니다.

2023-02-13 20:03 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/CategoryController.java
> +	@PostMapping("/admin/categories")
@s-jje 여기에 아마 어드민이 아닌 셀러나 고객이 사용하는 api 도 추가 예정이라, 그냥 둬도 될 것 같아요.

2023-02-13 20:16 UTC, mitoconcrete requested changes

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/CategoryResponse.java
> +@NoArgsConstructor
@jk891113 기본 생성자가 쓰이는 곳이 있나요..? 없다면, 지워도 될 것 같아요.
또한, 멤버변수의 값이 변경될 예정이 없다면 final로 선언해주셔도 좋을 것 같습니다.

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/ChildCategoryResponse.java
> +@NoArgsConstructor
@jk891113 기본 생성자가 쓰이는 곳이 있나요..? 없다면, 지워도 될 것 같아요.
또한, 멤버변수의 값이 변경될 예정이 없다면 final로 선언해주셔도 좋을 것 같습니다.

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/CreateCategoryRequest.java
> +	public CreateCategoryRequest(Long parentId, String name) {
@jk891113 Request 라면 클라이언트에서 갖고 들어오는 친구인데, 이 생성자를 컨트롤러나 서비스 내에서 할당해주는 부분이 없다면, 굳이 작성하지 않으셔도 될 것 같습니다! 이 역할은 기본생성자가 있다면 잭슨이 알아서 해주는 것으로 알고있습니다!

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/DeleteCategoryRequest.java
> +
@jk891113 Request 라면 클라이언트에서 갖고 들어오는 친구인데, 이 생성자를 컨트롤러나 서비스 내에서 할당해주는 부분이 없다면, 굳이 작성하지 않으셔도 될 것 같습니다! 이 역할은 기본생성자가 있다면 잭슨이 알아서 해주는 것으로 알고있습니다!

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/GetChildCategoryRequest.java
> +	public GetChildCategoryRequest(Long parentId) {
@jk891113 Request 라면 클라이언트에서 갖고 들어오는 친구인데, 이 생성자를 컨트롤러나 서비스 내에서 할당해주는 부분이 없다면, 굳이 작성하지 않으셔도 될 것 같습니다! 이 역할은 기본생성자가 있다면 잭슨이 알아서 해주는 것으로 알고있습니다!

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/UpdateCategoryControllerRequest.java
> +	public UpdateCategoryControllerRequest(String name) {
@jk891113 ControllerRequest 라면 클라이언트에서 갖고 들어오는 친구인데, 이 생성자를 컨트롤러나 서비스 내에서 할당해주는 부분이 없다면, 굳이 작성하지 않으셔도 될 것 같습니다! 이 역할은 기본생성자가 있다면 잭슨이 알아서 해주는 것으로 알고있습니다!

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/UpdateCategoryServiceRequest.java
> +@NoArgsConstructor
@jk891113 기본 생성자가 쓰이는 곳이 있나요..? 없다면, 지워도 될 것 같아요. 
또한, 멤버변수의 값이 변경될 예정이 없다면 final로 선언해주셔도 좋을 것 같습니다.

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/Category.java
> +	public static Category create(CreateCategoryRequest request) {
@jk891113 dto 가 엔티티까지 영향을 미치는 형태에 대해서 한번 고민해보셔도 좋을 것 같아요. 이 경우엔 클라이언트부터 엔티티까지 영향을 미치는 것인데, 레이아웃간 데이터를 주고 받는 역할을 담당하는 DTO의 역할이 거의 없는 것 같다고 느껴집니다.(엔티티까지 훅 들어오는 느낌)
저는 개인적으로 서비스에서 필요한 정보들만 까서 넣어주는 방식을 선호합니다.(개취입니다.)

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/entity/Category.java
> +	public void update(UpdateCategoryServiceRequest serviceRequest) {
@jk891113 dto 가 엔티티까지 영향을 미치는 형태에 대해서 한번 고민해보셔도 좋을 것 같아요. 이 경우엔 클라이언트부터 엔티티까지 영향을 미치는 것인데, 레이아웃간 데이터를 주고 받는 역할을 담당하는 DTO의 역할이 거의 없는 것 같다고 느껴집니다.(엔티티까지 훅 들어오는 느낌)
저는 개인적으로 서비스에서 필요한 정보들만 까서 넣어주는 방식을 선호합니다.(개취입니다.)

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/category/CategoryService.java
> +	void updateCategory(UpdateCategoryServiceRequest serviceRequest);
@jk891113 dto 가 엔티티까지 영향을 미치는 형태에 대해서 한번 고민해보셔도 좋을 것 같아요. 이 경우엔 클라이언트부터 엔티티까지 영향을 미치는 것인데, 레이아웃간 데이터를 주고 받는 역할을 담당하는 DTO의 역할이 거의 없는 것 같다고 느껴집니다.(엔티티까지 훅 들어오는 느낌)
저는 개인적으로 서비스에서 필요한 정보들만 까서 넣어주는 방식을 선호합니다.(개취입니다.)

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/category/CategoryService.java
> +	void deleteCategory(DeleteCategoryRequest request);
@jk891113 dto 가 엔티티까지 영향을 미치는 형태에 대해서 한번 고민해보셔도 좋을 것 같아요. 이 경우엔 클라이언트부터 엔티티까지 영향을 미치는 것인데, 레이아웃간 데이터를 주고 받는 역할을 담당하는 DTO의 역할이 거의 없는 것 같다고 느껴집니다.(엔티티까지 훅 들어오는 느낌)
저는 개인적으로 서비스에서 필요한 정보들만 까서 넣어주는 방식을 선호합니다.(개취입니다.)

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/category/CategoryServiceImpl.java
> +		Category category = this._getCategory(serviceRequest.getCategoryId());
@jk891113 this 는 제거하셔도 무방합니다!(개취입니다)

2023-02-13 20:16 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/category/CategoryServiceImpl.java
> +		Category category = this._getCategory(request.getCategoryId());
@jk891113 this 는 제거하셔도 무방합니다!(개취입니다)

2023-02-13 23:51 UTC, developer-Park approved these changes

2023-02-14 02:52 UTC, jk891113 commented on src/main/java/team/waitingcatch/app/restaurant/controller/CategoryController.java
> +	@PostMapping("/admin/categories")
@s-jje @mitoconcrete admin만 있을거 같기는 한데 일단은 그냥 두겠습니다.

2023-02-14 03:28 UTC, rianbowgift approved these changes

2023-02-14 03:35 UTC, jk891113 commented on src/main/java/team/waitingcatch/app/restaurant/dto/CreateCategoryRequest.java
> +	public CreateCategoryRequest(Long parentId, String name) {
@mitoconcrete 테스트 코드에 RequestDto 작성할 때 생성자를 사용했는데 일단 두고 다른 방법을 모색해 보겠습니다.

2023-02-14 03:47 UTC, mitoconcrete requested changes

2023-02-14 03:47 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/dto/CreateCategoryRequest.java
> +	public CreateCategoryRequest(Long parentId, String name) {
@jk891113 `CreateCategoryRequest request = mock(CreateCategoryRequest.class)` 와 같이
를 이용해 기본생성자없이 사용가능합니다. 테스트를 위해 기본생성자를 두는 것은 불필요하다고 생각듭니다!

2023-02-14 05:39 UTC, mitoconcrete approved these changes

2023-02-14 09:49 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/CreateCategoryRequest.java
> +public class CreateCategoryRequest {
@jk891113 코딩 컨벤션에 따라 클래스 명은 CreateCategoryControllerRequest가 되어야 될 것 같습니다.

2023-02-14 10:44 UTC, jk891113 commented on src/main/java/team/waitingcatch/app/restaurant/dto/CreateCategoryRequest.java
> +public class CreateCategoryRequest {
@s-jje 안 바뀌는 거는 레이어이름 안넣고 하나로 만드는거 아닌가여?

2023-02-14 10:46 UTC, s-jje approved these changes

2023-02-14 11:16 UTC, rianbowgift approved these changes

2023-02-14 11:16 UTC, merged