쿠폰,이벤트
mitoconcrete/waiting-catch-project pull request #125
Opened 2023-02-14 09:40 UTC by rianbowgift

리뷰 바랍니다.

2023-02-14 11:07 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +public class CouponController {
@rianbowgift 리소스를 생성하는 api는 api 명세서를 참고하셔서 응답값을 201로 내려주세요.

2023-02-15 03:17 UTC, mitoconcrete requested changes

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/event/InternalEventService.java
> +	public Restaurant _getRestaurantFindByUsername(String name);
@rianbowgift 컨벤션에 맞게 쓰기 위해서는 _getRestaurantByUsername 로 변경해주셔야해요!

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/event/InternalEventService.java
> +	public Restaurant _getRestaurantFindById(Long id);
@rianbowgift 컨벤션에 맞게 쓰기 위해서는 _getRestaurantById 로 변경해주셔야해요!

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +		return "광역 이벤트 쿠폰생성자를 수정하였습니다.";
@rianbowgift void 타입으로 변경해주세요.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +		Event events = internalEventService._getEventFindById(updateAdminCouponCreatorServiceRequest.getEventId());
@rianbowgift 사용하는곳이 없는데, 굳이 변수에 담을 필요는 없어보입니다!. validation 용 이라면, 그냥 담지않고 사용하시는편이 좋아보여요.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +		CouponCreator couponCreators = _getCouponCreatorFindById(updateAdminCouponCreatorServiceRequest.getCreatorId());
@rianbowgift 사용하는곳이 없는데, 굳이 변수에 담을 필요는 없어보입니다!. validation 용 이라면, 그냥 담지않고 사용하시는편이 좋아보여요.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		CreateCouponCreatorControllerRequest createCouponCreatorControllerRequest, @PathVariable Long eventId) {
@rianbowgift @RequestBody annotation 추가 필요합니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	public ResponseEntity<String> createSellerCouponCreator(
@rianbowgift @RequestBody annotation 추가 필요합니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		UpdateCouponCreatorControllerRequest updateCouponCreatorControllerRequest, @PathVariable
@rianbowgift @RequestBody annotation 추가 필요합니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		UpdateCouponCreatorControllerRequest updateCouponCreatorControllerRequest,
@rianbowgift @RequestBody annotation 추가 필요합니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +		Event events = eventServiceRepository.findByIdAndRestaurant(
@rianbowgift 단수형이 적절해보이고, event를 가져와서, 해당 이벤트의 레스토랑이 일치하는지 체크하는 메서드를 event 엔티티 내부에 구현하는 식으로 하는편이 쿼리가 덜 날라가지 않을까 생각됩니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +		CouponCreator couponCreators = _getCouponCreatorFindById(
@rianbowgift 단수형이 적절해보입니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		return ResponseEntity.status(HttpStatus.OK)
@rianbowgift status code는 201이 되어야 합니다. 전체 컨벤션을 맞추기위해 ResponseEntity 는 제거해도 좋을 것 같습니다!

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		return ResponseEntity.status(HttpStatus.OK)
@rianbowgift status code는 201이 되어야 합니다. 전체 컨벤션을 맞추기위해 ResponseEntity 는 제거해도 좋을 것 같습니다!

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		return ResponseEntity.status(HttpStatus.OK)
@rianbowgift status code는 201이 되어야 합니다. 전체 컨벤션을 맞추기위해 ResponseEntity 는 제거해도 좋을 것 같습니다!

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/usercoupon/CreateUserCouponServiceRequest.java
> +public class CreateUserCouponServiceRequest {
@rianbowgift 내부값이 변환될 확률이 없기 때문에, final로 선언해주셔도 좋을 것 같습니다.
추천 : RequiredArgsConstructor 를 이용하여, 가독성도 높힐 수 있습니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		User user = userRepository.findByUsername(createUserCouponserviceRequest.getUsername()).orElseThrow(
@rianbowgift UserService 에 _getUserByUsername 은 내부에서 validation 체크를 한 뒤, 엔티티를 뱉습니다. 그걸 사용하시는 편이 적절해보입니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/event/UpdateEventServiceRequest.java
> +public class UpdateEventServiceRequest {
@rianbowgift 내부값이 변환될 확률이 없기 때문에, final로 선언해주셔도 좋을 것 같습니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/event/UpdateSellerEventServiceRequest.java
> +public class UpdateSellerEventServiceRequest {
@rianbowgift 내부값이 변환될 확률이 없기 때문에, final로 선언해주셔도 좋을 것 같습니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/couponcreator/UpdateSellerCouponCreatorServiceRequest.java
> +public class UpdateSellerCouponCreatorServiceRequest {
@rianbowgift 내부값이 변환될 확률이 없기 때문에, final로 선언해주셔도 좋을 것 같습니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/event/CreateEventControllerRequest.java
> +public class CreateEventControllerRequest {
@rianbowgift  @NoArgsConstructor로 기본생성자를 명시적으로 선언해주셔도 좋을 것 같습니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/couponcreator/CreateSellerCouponCreatorServiceRequest.java
> +@Getter
@rianbowgift 내부값이 변환될 확률이 없기 때문에, final로 선언해주셔도 좋을 것 같습니다.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/couponcreator/CreateCouponCreatorControllerRequest.java
> +public class CreateCouponCreatorControllerRequest {
@rianbowgift 명시적으로 @NoArgsConstructor 를 선언해서 기본생성자를 선언해주는게 가독이 좋을 것 같아요.

2023-02-15 03:17 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/dto/couponcreator/CreateAdminCouponCreatorServiceRequest.java
> +public class CreateAdminCouponCreatorServiceRequest {
@rianbowgift 내부값이 변환될 확률이 없기 때문에, final로 선언해주셔도 좋을 것 같습니다.

2023-02-15 05:52 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/event/entity/Event.java
> +	public void isDeleted() {
이벤트 삭제여부 맞습니다. 혹시 활성화 비활성화방식으로 isStatus 등이 더좋을까요?  true/false 두개만 필요하기때문에 굳이 Status를 사용하지않아도 된다고 판단했습니다.

2023-02-15 06:09 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/entity/Event.java
> +	public void isDeleted() {
@rianbowgift 해당 메서드는 **삭제상태로 변경하는 메서드로** 보여지기 때문에, remove, delete 와 같은 네이밍도 좋다고 생각합니다. is~ / has~ 는 불리언값을 **반환**하는 형태일때 주로 사용되서요!

2023-02-15 10:46 UTC, mitoconcrete requested changes

2023-02-15 10:46 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	@PostMapping("/admin/events")
@rianbowgift  @ResponseStatus 를 사용하셔서 201를 반환해주세요.

2023-02-15 10:46 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	@PostMapping("/seller/restaurants/{restaurant_id}/events")
@rianbowgift @ResponseStatus 를 사용하셔서 201를 반환해주세요.

2023-02-15 10:46 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	@PostMapping("/admin/events/{eventId}/creator")
@rianbowgift @ResponseStatus 를 사용하셔서 201를 반환해주세요.

2023-02-15 10:46 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	@PostMapping("/seller/events/{eventId}/creator")
@rianbowgift @ResponseStatus 를 사용하셔서 201를 반환해주세요.

2023-02-15 10:46 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	@PostMapping("/restaurants/{restaurantId}/events/{eventId}/creators/{creatorId}")
@rianbowgift @ResponseStatus 를 사용하셔서 201를 반환해주세요.

2023-02-15 11:04 UTC, developer-Park approved these changes

2023-02-15 11:36 UTC, jk891113 approved these changes

2023-02-16 06:52 UTC, mitoconcrete approved these changes

2023-02-16 09:24 UTC, jk891113 approved these changes

2023-02-17 02:50 UTC, s-jje approved these changes

2023-02-17 02:51 UTC, merged