[merge] 유저,고객,판매자의 로그인, 로그아웃 구현 및 accesstoken, refreshtoken 플로우를 생성합니다.
mitoconcrete/waiting-catch-project pull request #128
Opened 2023-02-15 06:25 UTC by mitoconcrete

- 유저 로그인/로그아웃
- 고객 로그인/로그아웃
- 판매자 로그인/로그아웃
- access token 이 유효한 경우 그대로 서비스 진행
- access token 이 유효하지만, 이전에 로그아웃 내역이 있다면 에러반환 -> 로그아웃 
- access token 이 만료되었고, refresh token이 유효하다면 새로운 access token 생성
- access token 이 만료되었고, refresh token이 만료되었다면 에러반환 -> 로그아웃

2023-02-15 23:49 UTC, developer-Park approved these changes

2023-02-16 01:52 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/redis/service/AliveTokenServiceImpl.java
> +	private AliveToken _getAliveTokenByAccessToken(String AccessToken) {
Override해서 사용해야하지않나요?

2023-02-16 01:57 UTC, jk891113 requested changes

2023-02-16 01:57 UTC, jk891113 commented on src/main/java/team/waitingcatch/app/redis/service/AliveTokenServiceImpl.java
> +@Component
@mitoconcrete Service 어노테이션으로 바꿔도 되지 않을까요?

2023-02-16 02:11 UTC, rianbowgift approved these changes

2023-02-16 02:24 UTC, jk891113 approved these changes

2023-02-16 02:25 UTC, merged