[refactor] 레파지토리 및 블랙리스트,블랙리스트요청,셀러요청 부분
mitoconcrete/waiting-catch-project pull request #137
Opened 2023-02-18 03:31 UTC by developer-Park

- 레파지토리 및 블랙리스트,블랙리스트요청,셀러요청 부분 익셉션 처리, 리팩토링 및 엣지케이스 잡음.

2023-02-18 07:58 UTC, mitoconcrete requested changes

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/BlackListController.java
> +	public List<GetBlackListResponse> getBlackListByRestaurantId(@AuthenticationPrincipal UserDetailsImpl userDetails) {
@developer-Park 내부 로직을 타고 들어가보면 유저아이디를 가지고 레스토랑을 가지고 오는 것으로 확인되는데, dto명이나 메소드명이 기능과 일치하지 않아서 혼란이 있었습니다.
변경된 기능에 맞게 메소드와 dto 명을 수정해주세요!

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/RestaurantController.java
> +		System.out.println("###################확인해보기널값 레스토랑54" + multipartFile);
@developer-Park 로그는 제거 부탁드려요!

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/blacklist/BlackListServiceImpl.java
> +		System.out.println("###############" + blackListRequest.getUser().getId());
@developer-Park 로그는 제거해주세용

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestblacklist/BlackListRequestServiceImpl.java
> +		if (user.getRole() == UserRoleEnum.SELLER || user.getRole() == UserRoleEnum.ADMIN) {
@developer-Park 이건 시큐리티 단에서 컨트롤 가능할 것 같습니다!

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestblacklist/BlackListRequestServiceImpl.java
> +		if (blackListRequestCheck.size() >= 1) {
@developer-Park Optional로 뱉은 뒤 isPresent를 사용하는 형식으로 위에 사용하신 형식과 일치시켜주는 게 좋아보입니다.

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/restaurant/RestaurantServiceImpl.java
> +				if (Objects.equals(originalName, "기본값")) {
@developer-Park 해당 조건문은 Objects.equals(originalName, "기본값") == fasle 인 경우만 있는 상황으로 간소화 가능할 것같습니다.

2023-02-18 07:58 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/user/controller/UserController.java
> +		System.out.println(JwtUtil.AUTHORIZATION_HEADER + "#######" + loginServiceResponse.getAccessToken());
@developer-Park 이건 원래상태로 변경해주세요!

2023-02-18 12:02 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +		+ "and b.status = team.waitingcatch.app.restaurant.enums.AcceptedStatusEnum.APPROVAL")
@developer-Park 쿼리문이 길어지면 Querydsl을 사용을 고려해 주세요.

2023-02-18 12:02 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/restaurant/UpdateRestaurantEntityRequest.java
>  public class UpdateRestaurantEntityRequest {
@developer-Park 불필요한 검증 어노테이션들은 제거해 주세요.

2023-02-18 12:02 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/blacklist/DeleteUserBlackListByRestaurantServiceRequest.java
>  public class DeleteUserBlackListByRestaurantServiceRequest {
@developer-Park 불필요한 검증 어노테이션들은 제거해 주세요.

2023-02-18 12:02 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/blacklist/CancelRequestUserBlackListByRestaurantServiceRequest.java
>  public class CancelRequestUserBlackListByRestaurantServiceRequest {
@developer-Park 불필요한 검증 어노테이션들은 제거해 주세요.

2023-02-20 03:54 UTC, developer-Park commented on src/main/java/team/waitingcatch/app/restaurant/service/requestblacklist/BlackListRequestServiceImpl.java
> +		if (blackListRequestCheck.size() >= 1) {
@mitoconcrete List 와 optional을 같이 사용하는 방법이 있나요? optional을 앞에 사용하여 작성하니 for 문을 돌릴 수 없다고 나와서요

2023-02-20 04:40 UTC, developer-Park commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +	List<BlackListRequest> findByUser_IdAndRestaurant_User_Id(Long userId,
@s-jje 이것은 데이터가 누적이 되다보니 approval,wait,cancel 이런식으로 모든 데이터가 불러와져서 1개이상의 데이터가 넘어 오는것을 발견하고 그것을 처리하기 위하여 list로 받은후 for문을 돌려 안에 내용을 확인하는 방식으로 하였습니다.

2023-02-20 05:02 UTC, developer-Park commented on src/main/java/team/waitingcatch/app/restaurant/service/restaurant/RestaurantServiceImpl.java
> +				restaurantInfo.updateRestaurantInfo(updateRestaurantEntityRequest);
@s-jje 사이즈는 0을 대비해서 만들어 봤습니다. 그리고 바꾼이유는 convert때문에 바꿔봤습니다. 바꾸는 와중에 이중for문이 생겨 upload를 사용하여 구현해 보았습니다. uploadlist를 사용하면 list형식으로 url이 나오는데 그것들 다시 for로 풀어서 string 형태로 만든후 컴마를 붙여주는 형식이라 이중 for문이 돈다고 생각하였습니다.

2023-02-20 05:24 UTC, mitoconcrete requested changes

2023-02-20 05:24 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRepository.java
> +	@Query(value = "select b from BlackList b join fetch  b.user where b.restaurant.id =:res1")
@developer-Park 스페이스 바가 하나 더 있는 것 같아요!

2023-02-20 05:24 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/service/requestblacklist/BlackListRequestServiceImpl.java
> +		if (blackListRequestCheck.size() >= 1) {
@developer-Park Optional 에 존재하는 orElse를 이용해서 null일 경우 빈 배열을 넣어주게 만들면 반복문이 있어도 반복문을 돌지 않기 때문에 40번 라인의 조건문이 없어져도 되긴합니다. 똑같은 결로 현재 로직도 40번 조건문이 없어도 잘 동작할겁니다!

2023-02-20 05:24 UTC, mitoconcrete commented on src/main/resources/.vscode/settings.json
> +{
vscode 셋팅은 .gitignore에 추가하여 커밋에서 제외해주세요.

2023-02-20 06:18 UTC, mitoconcrete requested changes

2023-02-20 06:18 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/RequestBlackListController.java
> +	@PutMapping("/seller/blacklist-request/{requestBlackListId}")
@developer-Park 이전 포맷이 API 명세에 맞습니다!

2023-02-20 06:18 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/RequestBlackListController.java
> +	@PostMapping("/seller/blacklist-request/{userId}")
@developer-Park 이전 포맷이 API 명세에 맞습니다!

2023-02-20 07:54 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/restaurant/RestaurantServiceImpl.java
> +				restaurantInfo.updateRestaurantInfo(updateRestaurantEntityRequest);
이 부분은 제 PR merge 후 컨버터를 적용하시면 해결될 것 같습니다.

2023-02-20 07:54 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +	List<BlackListRequest> findByUser_IdAndRestaurant_User_Id(Long userId,
@developer-Park 이 부분은 가장 최근의 데이터만 불러오는 방식으로 바꾸는 것이 어떨까 합니다.

2023-02-20 08:53 UTC, jk891113 approved these changes

2023-02-20 09:52 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/APiController.java
@developer-Park 클래스 기능을 명확하게 알 수 있도록 클래스명을 XxxxApiController와 같이 바꿔주세요.

2023-02-21 01:26 UTC, rianbowgift approved these changes

2023-02-21 03:27 UTC, mitoconcrete approved these changes

2023-02-21 03:32 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +	@Query(value = "select b from BlackListRequest b where b.id =:user1 and b.restaurant.user.id =:seller1")
@developer-Park where 문에 b.id =: user1 이라고 되어있는데 BlackListRequest의 pk와 userId가 같은지를 비교하는 건가요?

2023-02-21 03:32 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +		+ "and b.status = team.waitingcatch.app.restaurant.enums.AcceptedStatusEnum.APPROVAL")
MVP 완성 후 적용 예정

2023-02-21 03:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRequestRepository.java
> +	BlackListRequest findByUser_IdAndRestaurant_User_IdAndStatus(@Param("user1") Long userId,
@developer-Park 메서드명만 보만 status까지 파라미터로 받을 수 있을 것 같은데 status가 approval로 고정이 되어있어서 메소드 명을 직관적으로 바꿔주시는게 좋을 것 같습니다.

2023-02-21 03:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/repository/BlackListRepository.java
> +	@Query(value = "select b from BlackList b where b.id =:user1 and b.restaurant.user.id =:seller1 and b.isDeleted =false")
@developer-Park BlackList의 id와 User의 id를 비교하고 있는 것 같습니다.

2023-02-21 09:50 UTC, s-jje commented on src/main/java/team/waitingcatch/app/admin/AdminController.java
> +		@ModelAttribute @RequestBody @Valid UpdateCategoryControllerRequest controllerRequest) {
@developer-Park @RequestBody를 지워주세요.

2023-02-21 09:50 UTC, s-jje commented on src/main/java/team/waitingcatch/app/config/SecurityConfig.java
> +			cors.addExposedHeader("Authorization");
@developer-Park 중복된 것 같습니다.

2023-02-21 09:50 UTC, s-jje commented on src/main/java/team/waitingcatch/app/user/repository/UserRepository.java
> +	Optional<User> findByUserId(@Param("userId") Long id);
@developer-Park findById를 사용하셔도 됩니다.

2023-02-22 11:47 UTC, merged