[refactor] 이벤트 조회시 쿠폰생성자 동시조회 수정 + 쿠폰조회 추가
mitoconcrete/waiting-catch-project pull request #138
Opened 2023-02-18 07:34 UTC by rianbowgift

확인해주세요~

2023-02-18 07:58 UTC, mitoconcrete approved these changes

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/dto/couponcreator/GetCouponCreatorResponse.java
> +	private LocalDateTime expireDate;
@rianbowgift 변경이 일어날 가능성이 없는 필드들은 final로 선언하는 것이 좋아보입니다.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/dto/usercoupon/GetUserCouponResponse.java
> +	private LocalDateTime expireDate;
@rianbowgift 변경이 일어날 가능성이 없는 필드들은 final로 선언하는 것이 좋아보입니다.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/dto/usercoupon/UserCouponResponse.java
> +	private CouponCreator couponCreator;
@rianbowgift 변경이 일어날 가능성이 없는 필드들은 final로 선언하는 것이 좋아보입니다.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		}
@rianbowgift 보유 쿠폰을 가져오고 각각의 쿠폰에 대한 쿠폰 생성자를 하나하나 가져오고 있는데 쿼리가 최대 N + 1번 발생하게 됩니다. 쿼리 최적화가 필요해 보입니다.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
>  	public List<GetEventsResponse> getEvents() {
@rianbowgift 응답을 List로 바로 내리시면 안되고 한번 감싸주셔야 합니다. 추후 common/dto의 GenericResponse를 이용하여 수정해 주세요.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
>  	public List<GetEventsResponse> getRestaurantEvents(@PathVariable Long restaurantId) {
@rianbowgift 응답을 List로 바로 내리시면 안되고 한번 감싸주셔야 합니다. 추후 common/dto의 GenericResponse를 이용하여 수정해 주세요.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
>  		List<GetEventsResponse> GetEventsResponse = new ArrayList<>();
@rianbowgift 지역변수의 첫글자를 소문자로 바꿔주세요.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
>  		List<GetEventsResponse> GetEventsResponse = new ArrayList<>();
@rianbowgift 지역변수의 첫글자를 소문자로 바꿔주세요.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
> +	public List<GetEventsResponse> _GetEventsResponse(List<Event> events, List<GetEventsResponse> GetEventsResponse) {
@rianbowgift List<GetEventsResponse>는 굳이 파라미터로 받을 필요없이 리턴값으로 주기 때문에 필요없을 것 같습니다.

2023-02-18 12:23 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
> +		}
@rianbowgift 이벤트를 조회하여 이 메소드에서 각 이벤트에 대한 쿠폰 생성자를 조회하는 로직으로 보여지는데 N + 1 문제가 발생합니다. 쿼리 최적화를 해주세요.

2023-02-20 00:40 UTC, mitoconcrete requested changes

2023-02-20 00:40 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/event/InternalEventService.java
> +	List<GetEventsResponse> _GetEventsResponse(List<Event> events, List<GetEventsResponse> GetEventsResponse);
@rianbowgift 메서드명 앞글자는 소문자로 변경해주세요. 추가적으로 내부 서비스는 dto가 아닌 엔티티를 반환해야 합니다.
List<Event> 와 같이 리턴타입을 변경해주세요

2023-02-20 00:40 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +	public void GetUserCoupon(@AuthenticationPrincipal UserDetailsImpl userDetails) {
@rianbowgift 메서드 명 첫글자는 소문자가 되어야 하고, 조회이기 때문에 GetMapping을 이용해야합니다. 또한 단일 쿠폰내역만 가져오는 것이 아니기때문에 복수형으로 선언하는것이 적절해보입니다.

2023-02-20 00:40 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponService.java
> +	List<GetUserCouponResponse> getUserCoupon(User user);
@rianbowgift List반환이기 때문에 복수형이 되어야할 것 같습니다!

2023-02-20 08:54 UTC, jk891113 approved these changes

2023-02-21 03:15 UTC, developer-Park approved these changes

2023-02-21 03:28 UTC, mitoconcrete approved these changes

2023-02-21 03:52 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
> +		}
MVP 완성 후 수정 예정

2023-02-21 03:52 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		}
MVP 완성 후 수정 예정

2023-02-21 03:54 UTC, merged