[Refactor] 셀러페이지 오류수정 및 유저디테일작업
mitoconcrete/waiting-catch-project pull request #172
Opened 2023-02-28 02:39 UTC by rianbowgift

고정값의 유저를 받아오는 셀러페이지가 로그인된 유저를 재대로 받아오게 수정되었습니다. DTO는 대부분 그대로 사용할수있게 수정하였고 서비스단에서 로직이틀렸거나 잘못된값을 받아오는것을 조금 수정하였습니다.
 쿠키재발급관련 이슈 미해결입니다.

2023-02-28 07:02 UTC, mitoconcrete requested changes

2023-02-28 07:02 UTC, mitoconcrete commented on src/main/resources/templates/login.html
> +                    todayDate.setDate(todayDate.getDate() + 30); // 현재 시각 + 일 단위로 쿠키 만료 날짜
엑세스 토큰의 유효 기간이 30분이라서, 30분 뒤로 expires를 설정해놓으시면 될겁니다!

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/entity/CouponCreator.java
> +			this.quantity = this.quantity - 1;
@rianbowgift -= 또는 -- 연산자를 사용하면 더 깔끔할 것 같아요!

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/entity/CouponCreator.java
> +	public boolean createCoupon() {
@rianbowgift 메서드 명이 명확하지 않은 것 같아요.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +			String restaurantName = userCoupon.getCouponCreator().getEvent().getRestaurant().getName();
@rianbowgift N + 1 이 발생합니다.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		}
@rianbowgift 동시성 문제를 고려해 주세요.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/MenuController.java
>  		@RequestPart("images") MultipartFile multipartFile,
@rianbowgift @RequestPart는 default 값이 required = true 이므로 required = false로 설정해 주세요. 저희 ERD 상에 이미지는 nullable 합니다.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
>  		@RequestPart("image") MultipartFile multipartFile,
@rianbowgift @RequestPart는 default 값이 required = true 이므로 required = false로 설정해 주세요. 저희 ERD 상에 이미지는 nullable 합니다.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
> +		@RequestPart("image") MultipartFile multipartFile,
@rianbowgift 메뉴 업데이트 시 이미지를 꼭 받아야 하는 것이 아니라면 required = false로 설정해 주세요.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
> +		@RequestPart("image") List<MultipartFile> multipartFile,
@rianbowgift required = false로 설정해 주세요.

2023-02-28 08:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/dto/restaurant/UpdateRestaurantControllerRequest.java
> +@Setter
@rianbowgift setter 대신 생성자를 사용해 주세요.

2023-02-28 22:09 UTC, developer-Park approved these changes

2023-03-02 03:26 UTC, jk891113 approved these changes

2023-03-02 13:24 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/MenuController.java
> +		@RequestPart("requestDto") @Valid UpdateMenuControllerRequest request,
@rianbowgift @RequestPart는 required = false로 설정해 주세요.

2023-03-03 02:58 UTC, mitoconcrete commented on src/main/resources/templates/login.html
> +                    todayDate.setDate(todayDate.getDate() + 30); // 현재 시각 + 일 단위로 쿠키 만료 날짜
`new Date().getTime() + 1000 * 60 * 30`

2023-03-03 03:43 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/restaurant/controller/MenuController.java
> +		@RequestPart("requestDto") @Valid UpdateMenuControllerRequest request,
현재 사용되지않는 컨트롤러고, 제가짠부분이 아니라 남겨뒀습니다!

2023-03-03 03:44 UTC, rianbowgift commented on src/main/java/team/waitingcatch/app/restaurant/controller/MenuController.java
>  		@RequestPart("images") MultipartFile multipartFile,
현재 사용되지않는 컨트롤러고, 제가짠부분이 아니라 남겨뒀습니다!

2023-03-03 07:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/UserCouponRepository.java
> +	UserCoupon findUserCouponWithRelations(@Param("user") User user,
@rianbowgift 단건 조회는 Optional로 받아주세요.

2023-03-03 07:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/UserCouponRepository.java
> +	@Query("select uc from UserCoupon uc join fetch uc.user join fetch uc.couponCreator cc join fetch cc.event e join fetch e.restaurant r where uc.user = :user and uc.couponCreator = :couponCreator")
@rianbowgift User, CouponCreator, Event, Restaurant을 전부 fetch join으로 가져오시는 이유가 있으신가요? 

fetch join은 와일드카드(*)로 select 쿼리가 나가게 됩니다. 따라서 각 테이블의 모든 컬럼을 select 쿼리로 가져옵니다. CouponCreator 말고는 사용되는 곳이 없어 보이는데 fetch join으로 가져오신 연관된 엔티티 객체 그래프 전체가 필요 없다면 join로 바꿔주세요.

2023-03-03 07:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +			String restaurantName = userCouponRepository.findRestaurantNameByUserCoupon(userCoupon);
@rianbowgift 하나하나 select 해서 가져오는 것보다는 in 절을 사용하셔서 한 번에 가져오는 것을 고려해 주세요.

2023-03-03 07:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/entity/CouponCreator.java
> +			this.quantity -= 1;
@rianbowgift 메서드 명을 보면 단순히 쿠폰 재고 존재 여부를 반환하는 함수로 보여집니다. 
UserCoupone.issueCoupone()에서는 단순히 이 메서드를 리턴만 하고 있는데 재고 존재 여부 확인, 재고 감소 로직을 명확하게 분리하는 것이 좋아보입니다.

2023-03-03 07:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/entity/UserCoupon.java
> +	public synchronized boolean issueCoupon() {
@rianbowgift 여기에 synchronized를 사용하셔도 @Transactional의 동작 방식 때문에 해당 메서드 실행 후 트랜잭션이 커밋되어 DB에 반영되기 전에 다른 쓰레드에서 접근이 가능해 집니다. 따라서 동시성 문제는 여전히 발생합니다.

2023-03-03 07:58 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		}
@rianbowgift Spring Retry를 사용하시면 위 로직을 더 깔끔하게 바꿀 수 있습니다!

2023-03-03 08:03 UTC, mitoconcrete approved these changes

2023-03-03 13:30 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +	String recover(IllegalArgumentException e) {
@rianbowgift 리턴 타입은 @Retry가 붙은 메서드의 리턴 타입과 동일해야 됩니다. ControllerAdvice로 예외를 받아서 메시지를 보여줄 수 있게 예외를 던지는 것도 좋을 것 같습니다.

2023-03-03 13:30 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		Optional<UserCoupon> userCoupon = null;
@rianbowgift 미리 null로 초기화가 필요 없을 것 같습니다.

2023-03-03 13:43 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +	@Transactional(isolation = Isolation.READ_COMMITTED)    //트랜잭션이 commit 되어 확정된 데이터만을 읽도록 허용
@rianbowgift read commited을 적용하신 이유가 있으실까요? MySQL 기본 트랜잭션 격리 수준이 repeatable read로 read commited 보다 한 단계 더 높습니다.

2023-03-03 13:43 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +	String recover(IllegalArgumentException e) {
@rianbowgift @Recover에서는 낙관적 락 획득 실패 시 발생하는 예외인 OptimisticLockingFailureException을 받아주셔야 합니다.

2023-03-04 16:45 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/entity/UserCoupon.java
> +	// }
@rianbowgift 불필요한 주석은 지워주세요.

2023-03-04 16:45 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		//Optional<UserCoupon> userCoupon = userCouponRepository.findUserCouponWithRelations(user, couponCreator);
@rianbowgift 불필요한 주석은 지워주세요.

2023-03-04 16:45 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		// }
@rianbowgift 불필요한 주석은 지워주세요.

2023-03-04 16:49 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
>  		}
@rianbowgift 스트림을 적용하면 가독성이 더 좋을 것 같아요.

2023-03-04 16:49 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
>  		// 	//유저쿠폰을 담기위한 리스폰스를 만든다
@rianbowgift 불필요한 주석들은 지워주세요.

2023-03-04 16:49 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/UserCouponRepository.java
@rianbowgift 주석 정리해 주세요.

2023-03-06 00:58 UTC, mitoconcrete requested changes
@rianbowgift 이미지 파일 모두 제거해주세요~~

2023-03-06 01:51 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> -@RequestMapping("/api")
@rianbowgift 이 부분을 제거하고 아래에 하나하나 붙이신 이유가 있을까요?

2023-03-06 01:51 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/dto/usercoupon/GetUserCouponResponse.java
> +	// }
@rianbowgift 불필요한 주석은 제거해 주세요.

2023-03-06 01:51 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/menu/MenuServiceImpl.java
> +				imageUrl = imageUploader.upload(serviceRequest.getMultipartFile(), "menu");
@rianbowgift 이 부분은 이전 코드인 common/enums/ImageDirectoryEnum을 사용해 주세요!

2023-03-06 01:51 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +			.map(response -> new GetUserCouponResponse(response))
@rianbowgift findRestaurantNameAndUserAll()의 쿼리를 보면 단순 join을 하고 있는데 GetUserCouponResponse의 내부를 보면 .getXxx(). ... 이 사용되고 있어 N + 1 문제가 발생합니다.

2023-03-06 01:51 UTC, s-jje commented on src/main/java/team/waitingcatch/app/exception/ApplicationExceptionController.java
> +	}
@rianbowgift @Recover를 제거하고 @ExceptionHandler를 사용하신 이유가 있으신가요?

2023-03-06 02:14 UTC, mitoconcrete approved these changes

2023-03-06 06:31 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/entity/UserCoupon.java
> +	private Long version;
@rianbowgift UserCoupon은 각 유저가 따로 가지고 있으므로 버전 관리가 무의미 합니다. 낙관적 락은 쿠폰 수량을 체크하는 CouponCreator에 걸어야 됩니다.

2023-03-06 15:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		return eventService.getGlobalEvents(0L, pageable);
@rianbowgift 0L 이라는 특정 값을 넣어주신 이유가 있으신가요?

2023-03-06 15:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/controller/CouponController.java
> +		return eventService.getGlobalEvents(0L, pageable);
@rianbowgift 0L 이라는 특정 값을 넣어주신 이유가 있으신가요?

2023-03-06 15:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
> +		System.out.println(serviceRequest.getEventId() + "  " + restaurant + " 검증");
@rianbowgift logger를 사용해 주세요.

2023-03-06 15:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
> +	public Page<GetEventsResponse> getGlobalEvents(Long restaurantId, Pageable pageable) {
@rianbowgift 글로벌 이벤트는 restaurantId가 null인 event 아닌가요?

2023-03-06 15:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/restaurant/RestaurantServiceImpl.java
> +		System.out.println(restaurantId + "검증아이디");
@rianbowgift logger를 사용해 주세요.

2023-03-06 15:46 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/couponcreator/CouponCreatorServiceImpl.java
>  			.orElseThrow(() -> new IllegalArgumentException("매장에 해당 이벤트가 존재하지 않습니다."));
@rianbowgift  ErrorCode의 NOT_FOUND_EVENT를 NoSuchElementException에 사용하는 것으로 바꿔주세요.

2023-03-06 16:08 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/UserCouponRepository.java
> +		@Param("couponCreator") CouponCreator couponCreator);
@rianbowgift 낙관적 락은 jpa가 지원하는 기능입니다. 따라서 @Version이 있는 CouponCreator가 엔티티로 조회되어야 version 컬럼이 증가합니다. 참고하셔서 로직을 수정해 주세요.

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/CouponCreatorRepository.java
> +	int getHasCouponBalance(@Param("id") Long id);
@rianbowgift 낙관적 락은 jpa에서 지원하는 기능이기 때문에 엔티티 자체로 조회해야 영속성 컨텍스트에 저장되어 버전 정보가 업데이트 됩니다.

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
> +		Restaurant restaurant = null;
@rianbowgift 사용하지 않는 변수는 지워주세요.

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +				throw new IllegalStateException(DUPLICATE_COUPON.getMessage());
@rianbowgift Custom 예외인 DuplicateRequestException을 사용해 주세요.

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +		if (isCouponIssued > 0) {
@rianbowgift 변수명만 봤을때는 boolean 타입인 것 같습니다. 명확하게 바꿔주세요!

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/repository/EventRepository.java
> +	Page<Event> findByRestaurantIsNull(Pageable pageable);
@rianbowgift 삭제 처리된 이벤트는 조회되지 않도록 해주세요.

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/event/EventServiceImpl.java
>  		for (Event event : events) {
@rianbowgift N + 1 이 발생합니다.

2023-03-07 01:47 UTC, s-jje commented on src/main/java/team/waitingcatch/app/event/service/usercoupon/UserCouponServiceImpl.java
> +	@Retryable(maxAttempts = 3, backoff = @Backoff(10000), value = OptimisticLockingFailureException.class)
@rianbowgift 0.1초마다 재시도하는 로직에서 10초마다 재시도하게 바뀌었는데 텀이 조금 긴 것 같습니다.

2023-03-07 07:25 UTC, merged