카테고리 매핑 테이블 기능 추가, 레스토랑 Address 변경
mitoconcrete/waiting-catch-project pull request #173
Opened 2023-02-28 05:00 UTC by jk891113

레스토랑 Address 값 변경에 따라 레스토랑 조회 등의 프론트에서의 response 데이터 수정이 필요할 듯 합니다.

2023-02-28 06:53 UTC, mitoconcrete requested changes

2023-02-28 06:53 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/CategoryController.java
> +	public List<CategoryResponse> getParentCategoriesForSellerManagement() {
@jk891113 List 형식은 GenericResponse 에 담아주시면 됩니다!

2023-02-28 06:53 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/CategoryController.java
>  	public List<CategoryResponse> getChildCategoriesForSellerManagement(@PathVariable Long categoryId) {
@jk891113 List 형식은 GenericResponse 에 담아주시면 됩니다!

2023-02-28 10:14 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/category/CategoryServiceImpl.java
> +	public void connectCategoryRestaurant(ConnectCategoryRestaurantServiceRequest serviceRequest) {
@jk891113 이 메서드가 어디서 사용되어 지나요?

2023-02-28 22:09 UTC, developer-Park approved these changes

2023-03-01 04:40 UTC, jk891113 commented on src/main/java/team/waitingcatch/app/restaurant/service/category/CategoryServiceImpl.java
> +	public void connectCategoryRestaurant(ConnectCategoryRestaurantServiceRequest serviceRequest) {
@s-jje 판매자요청 승인할 때 레스토랑이 생성되면 레스토랑 Id와 선택한 카테고리 Id를 CategoryRestaurant 테이블에 넣어줄때 사용합니다.

2023-03-02 02:32 UTC, mitoconcrete approved these changes

2023-03-02 02:50 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/service/category/InternalCategoryService.java
> +	void connectCategoryRestaurant(ConnectCategoryRestaurantServiceRequest serviceRequest);
@jk891113 InternalService의 메서드에는 prefix로 _를 붙여주세요.

2023-03-02 02:50 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/SellerManagement.java
>  	@Column(name = "business_license_no", nullable = false)
@jk891113 name은 굳이 안적어주셔도 됩니다.

2023-03-02 02:50 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/SellerManagement.java
>  	private String categories;
@jk891113 @Converter를 적용해 주세요.

2023-03-02 05:48 UTC, rianbowgift approved these changes

2023-03-02 12:41 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
>  	private String searchKeywords;
@jk891113 여기에 컨버터를 적용하면 좋을 것 같습니다.

2023-03-02 13:03 UTC, jk891113 commented on src/main/java/team/waitingcatch/app/restaurant/entity/Restaurant.java
>  	private String searchKeywords;
@s-jje 이거는 정훈님이 Converter 처리 하신듯 합니다.

2023-03-02 22:44 UTC, developer-Park approved these changes

2023-03-03 02:59 UTC, merged