[merge] 줄서기에 낙관적 락으로 변경 및 페이징 처리
mitoconcrete/waiting-catch-project pull request #174
Opened 2023-02-28 10:01 UTC by s-jje

1. 줄서기 시 비관적 락에서 낙관적으로 변경
  - 요청 실패 시 최대 3번 시도 후 예외 반환하도록 변경
2. 줄서기 히스토리 및 리뷰 조회 시 slice 페이징 처리 적용

2023-02-28 11:00 UTC, mitoconcrete requested changes
@s-jje 코드 모두 확인했습니다.
우려되는 점이 있다면, 지금 마지막 레코드의 아이디를 들고 있다가, 그걸 전달하는식으로 페이징을 하는 식으로 구성이 되어있는데, 다음페이지로 가는건 상관없지만, 이전페이지로 이동하는 기능을 수행할때 클라이언트에서 처리할게 많아질 것 같다는 걱정이 들어요.

[이 페이지](https://stackoverflow.com/a/3799223) 보시면, mysql에서 limit 에 start, end offset을 걸어서 데이터를 가져오는것이 가능하던데, 이 방법을 사용하시면 이전페이지나 다음페이지로 이동하는 로직이 자연스러워질 수 있겠다는 생각이 들어요! 또한, 스프링에서도 pageable을 넘길 때 List로 반환받게 되면, limit offset을 이용해처리를 하는 것으로 보입니다!
혹시나 전략이 있으시다면, 상관없지만, 페이지 전후이동에 대한 전략이 확실하지 않으셨다면, 위 방법으로 변경해보시는 것을 추천드립니다!

2023-02-28 11:59 UTC, mitoconcrete approved these changes

2023-02-28 12:03 UTC, mitoconcrete requested changes
@s-jje [url규칙](https://www.notion.so/S-A-e0603e170f0f4a9da949ad475682a2d9#faf79aa64f21499a9ff752f1f7c4a950) 이 변경되어서, 확인하시고 그에따라 controller url 변경 부탁드립니다!

2023-02-28 22:09 UTC, developer-Park approved these changes

2023-03-02 06:14 UTC, mitoconcrete requested changes

2023-03-02 06:14 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/ReviewController.java
>  	@GetMapping("/restaurants/{restaurantId}/reviews")
@s-jje 여기 url 포맷 변경해주세용

2023-03-02 06:15 UTC, developer-Park approved these changes

2023-03-02 06:29 UTC, mitoconcrete requested changes

2023-03-02 06:29 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/LineupController.java
> +	@GetMapping("/general/seller/lineup")
@s-jje  이 친구는 로그인 이후, 토큰 검증을 통해 셀러만 호출할 수 있는 api라서, general을 제거해주시는게 합의된 포맷에 맞습니다!

2023-03-02 06:29 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/ReviewController.java
> +	@DeleteMapping("/general/admin/review/{reviewId}")
@s-jje  이 친구는 로그인 이후, 토큰 검증을 통해 어드민만 호출할 수 있는 api라서, general을 제거해주시는게 합의된 포맷에 맞습니다!

2023-03-02 06:29 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/ReviewController.java
> +	@GetMapping("/general/restaurants/{restaurantId}/reviews")
@s-jje  이 친구는 로그인 이후, 토큰 검증을 통해 유저만 호출할 수 있는 api라서, general을  customer 로 변경해주시는게 합의된 포맷에 맞습니다!

2023-03-02 06:29 UTC, rianbowgift approved these changes

2023-03-02 06:38 UTC, mitoconcrete approved these changes

2023-03-02 06:39 UTC, mitoconcrete requested changes

2023-03-02 06:39 UTC, mitoconcrete commented on .github/workflows/gradle-ci.yml
> +  push:
@s-jje 엇 성제님 feature/** 로 변경해주시는게 의도 아니셨나요??

2023-03-02 06:47 UTC, mitoconcrete approved these changes

2023-03-02 07:11 UTC, merged