Restaurant 조회 부분 페이징 구현
mitoconcrete/waiting-catch-project pull request #181
Opened 2023-03-03 09:28 UTC by jk891113

2023-03-03 13:02 UTC, developer-Park approved these changes

2023-03-04 10:20 UTC, developer-Park approved these changes

2023-03-04 16:49 UTC, mitoconcrete requested changes

2023-03-04 16:49 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/repository/querydsl/RestaurantInfoRepositoryCustomImpl.java
> +			.limit(pageable.getPageSize() + 1)
@jk891113 이렇게 되면 다음 페이지를 부르는 트리거가 없는거 아닌가요..? 성제님은 마지막 데이터의 아이디를 넘기는 식으로 구현해놓으셨던데, 그런장치가 필요하진 않을까요?

2023-03-04 16:49 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/repository/querydsl/RestaurantInfoRepositoryCustomImpl.java
> +			.limit(pageable.getPageSize() + 1)
@jk891113 이렇게 되면 다음 페이지를 부르는 트리거가 없는거 아닌가요..? 성제님은 마지막 데이터의 아이디를 넘기는 식으로 구현해놓으셨던데, 그런장치가 필요하진 않을까요?

2023-03-05 16:07 UTC, s-jje approved these changes

2023-03-06 00:43 UTC, mitoconcrete approved these changes

2023-03-06 00:43 UTC, merged