[merge] 판매자 블랙리스트 신청 페이지 구현
mitoconcrete/waiting-catch-project pull request #184
Opened 2023-03-03 19:11 UTC by s-jje

2023-03-04 09:38 UTC, mitoconcrete requested changes
@s-jje contoller 포맷이 합의된 형식에 맞지않는 부분이 있고, 그것이 변경됨에 따라 템플릿들에 영향을 주는 곳이 많을 것 으로 보여집니다. 따라서, 번거로우시겠지만, 아래의 과정을 통해 전체적으로 수정을 해주시면 좋을 것 같습니다.

1) [해당링크](https://www.notion.so/S-A-e0603e170f0f4a9da949ad475682a2d9?pvs=4#7ad43f3764944dc7a8f924483bbcb313)를 참고하여, 작업하신 api와 프론트에 연결된 url 들의 포맷을 수정한다.

2) 수정한 url에 맞게 프론트가 동작하도록 한다.

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/LineupApiController.java
> +	@PostMapping("/restaurants/{restaurantId}/lineup")
@s-jje 고객이 사용하는 api 같은데, /api/customer/restaurants/{restaurantsId}/lineup 으로 변경해주셔야합니다.

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/LineupApiController.java
> +	@DeleteMapping("/restaurants/lineup/{lineupId}")
@s-jje 고객이 사용하는 api 같은데, /api/customer/restaurants/{restaurantsId}/lineup 으로 변경해주셔야합니다.

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/LineupApiController.java
> +	public GenericResponse<List<LineupRecordWithTypeResponse>> getLineupRecords(
@s-jje 페이지가 분리되었으니, Slice로 주셔야 할 듯 합니다! List로하신 의도가 있을까요?

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/lineup/controller/LineupController.java
>  	@GetMapping("/seller/lineup")
@s-jje  /seller/templates/lineup 이 되어야 적절해보입니다!

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/BlacklistDemandController.java
> +	@GetMapping("/seller/blacklist-demands")
@s-jje /seller/templates/~ 형식이 되어야합니다!

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
> +	@GetMapping("/seller/info")
@s-jje /seller/templates/info 가 되어야합니다!

2023-03-04 09:38 UTC, mitoconcrete commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
> +	@PutMapping("/seller/info")
@s-jje /api/seller/info 가 되어야합니다!

2023-03-04 10:22 UTC, developer-Park approved these changes

2023-03-04 15:28 UTC, s-jje commented on src/main/java/team/waitingcatch/app/lineup/controller/LineupApiController.java
> +	public GenericResponse<List<LineupRecordWithTypeResponse>> getLineupRecords(
@mitoconcrete  이 api는 lineup 테이블에서 그날 하루의 줄서기 내역을 가져오는 것이기 때문에 페이징이 불필요하다고 생각합니다.

2023-03-04 15:28 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
> +	@GetMapping("/seller/info")
@mitoconcrete 이 부분은 경헌님 파트라 그냥 두겠습니다.

2023-03-04 15:28 UTC, s-jje commented on src/main/java/team/waitingcatch/app/restaurant/controller/SellerController.java
> +	@PutMapping("/seller/info")
@mitoconcrete 이 부분은 경헌님 파트라 그냥 두겠습니다.

2023-03-04 16:41 UTC, mitoconcrete approved these changes

2023-03-05 01:52 UTC, rianbowgift approved these changes

2023-03-05 06:35 UTC, merged